config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  devise_for :users
  resources :users do
    member do
      post :downgrade
    end
  end
  get 'charges/create'
  get 'welcome/index'
  get 'welcome/about'
  devise_for :wikis
  resources :wikis
  resources :charges, only: [:new, :create]
end


# { confirmations: 'confirmations' }

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum role: [:standard, :admin, :premium] 

  devise :confirmable, :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  after_initialize :set_default_role 

  def set_default_role
    self.role ||= :standard
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base

  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  scope :visible_to, -> (user) { user ? where(private: false) : 'There was an error.' }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 include Pundit
  before_action :authenticate_user!
  protect_from_forgery with: :exception

   rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to :back || root_path
  end
  
end

app/controllers/charges_controller.rb
# def create
#    # Creates a Stripe Customer object, for associating
#    # with the charge
#    customer = Stripe::Customer.create(
#      email: current_user.email,
#      card: params[:stripeToken]
#    )
 
#    # Where the real magic happens
#    charge = Stripe::Charge.create(
#      customer: customer.id, # Note -- this is NOT the user_id in your app
#      amount: Amount.default,
#      description: "BigMoney Membership - #{current_user.email}",
#      currency: 'usd'
#    )
 
#    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
#    redirect_to user_path(current_user) # or wherever
 
#    # Stripe will send back CardErrors, with friendly messages
#    # when something goes wrong.
#    # This `rescue block` catches and displays those errors.
#    rescue Stripe::CardError => e
#      flash[:alert] = e.message
#      redirect_to new_charge_path
#  end

#   def new
#    @stripe_btn_data = {
#      key: "#{ Rails.configuration.stripe[:publishable_key] }",
#      description: "BigMoney Membership - #{current_user.name}",
#      amount: Amount.default
#    }
#  end

 class ChargesController < ApplicationController

  def create
    @user = current_user
    
    #Creates a Stripe Customer object, for associating with the charge.
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

  # Payment being made
  charge = Stripe::Charge.create(
    customer: customer.id,
    amount: 10_00,
    description: "Upgrade to Premium Membership - #{current_user.email}",
    currency: 'usd'
  )

  @user.update_attributes(role: 'premium')
  @user.role = 'premium'
  @user.save

  flash[:notice] = "Thanks for the payment, #{current_user.email}! You can now create and edit private wikis."
  redirect_to root_path

  # Stripe will send back CardErrors, with friendly messages when something goes wrong.
  # This `rescue block` catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      # description: "Premium Membership - #{current_user.name}",
      amount: 10_00
    }
  end

  private

  def upgrade_user_role
    @user.role = 'premium'
  end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  # private
  # def after_confirmation_path_for(resource_name, resource)
  #   your_new_after_confirmation_path
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :js
  include ActiveModel::AttributeMethods
  def update
  	@user = User.find(params[:id])
    name = @user.name
  end

  def edit 
  end 
  
  def show
    if current_user.present?
      @user = params[:id] ? User.find(params[:id]) : current_user
    else
      redirect_to root_path
    end
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def downgrade
    @user = User.find(params[:id])
    @user.role = 'standard'

    if @user.save
      flash[:notice] = "You've been downgraded to standard. Your private wikis are now public."
      redirect_to :back
    else
      flash[:error] = "There was an error creating your account. Please try again."
      redirect_to :back
    end

    @user_wikis = @user.wikis.where(private: true)

    @user_wikis.each do |makepub|
      makepub.update_attributes(private: false)
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_filter :authenticate_user!, except: [ :index, :about ]

  def index
  end

  def about
  end

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  include ApplicationHelper

  # before_filter :authenticate_user!

  # after_action :verify_authorized, :except => :index

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @user = current_user
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @user = current_user
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      redirect_to @wiki, notice: "Wiki was saved successfully."
    else
      flash[:error] = "Error creating wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
    # @collaborator = Collaborator.new
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    @wiki.assign_attributes(wiki_params)
    @wiki.user_ids = params[:wiki][:user_ids] if params[:wiki][:user_ids].present?

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash[:error] = "Error saving wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash[:error] = "There was an error deleting the wiki."
      render :show
    end
  end

 private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :user, :user_ids)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper



  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h4>Upgrade to a premium Plan</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

 <img id="moneybags" src="http://www.palmbeachdailynews.com/rf/image_lowres/Pub/p8/PalmBeachDailyNews/2017/01/26/Images/newsEngin.17470261_Money-bags.jpg">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


		<%= yield %>

		<% if user_signed_in? %>
		   Signed in as: <strong><%= current_user.email %></strong> |
		   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

		 <% else %>
		   <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
		   <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
		 <% end %> 

<!-- 

	<p class="navbar-text pull-right">
		<% if user_signed_in? %>
  			Logged in as <strong><%= current_user.email %></strong>.
  			<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
  			<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  			<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>
	</p> -->



</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<ol class="breadcrumb">
    <li><%= link_to "Home", welcome_index_path %></li>
    <% if user_signed_in? %>
    <li> </li>  
    <% else %>      
    <li><%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %></li>
  <% end %> 
  <li class="pull-right"><%= link_to "Edit Profile", edit_user_registration_path %></li>
</ol>
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron" id="about-all">
      <div class="container">
        <h1 class="display-3">Wikipedia, without the contributors.</h1>
        <p><a class="btn btn-success btn-lg" href="#" role="button">Create a Wiki</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Free</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Collaborative</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Private (Premium)</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

app/views/welcome/index.html.erb
<div id="wiki-index-all">
<ol class="breadcrumb">
    <li><%= link_to "About", welcome_about_path %></li>
    <% if user_signed_in? %>
    <li> </li>  
    <% else %>      
    <li><%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %></li>
  <% end %> 
  <li class="pull-right"><%= link_to "Edit Profile", edit_user_registration_path %></li>
</ol>


<div class="heading">
  <h1 id="index-title"> <span id="index-bloc"> Bloc</span>ipedia</h1>

  <div class="box">
    <h3 id="index-slogan"> Create Wikis with Friends for FREE. Keep them private a penny per month. </h3>
  </div>
</div>


<div class="row" id="index-wikis">
  <div class="col-md-6">
    <h4 class="free-location"> Create Public Wikis </h4>
    <div class="free-button">
      <%= link_to "Public Wikis", wikis_path, class: 'btn btn-success' %>
    </div>
  </div>

 

  <div class="col-md-5">
    <h4 class='premium-location'> Create Private Wikis </h4>
    <div class='premium-button'>
    <% if current_user.role == 'premium' || current_user.role == 'admin' %>
        <%= link_to "Private Wikis", new_charge_path, class: 'btn btn-success' %>
      <% else %>
        <%= link_to "Upgrade to Premium!", edit_user_registration_path, class: 'btn btn-info' %>
      <% end %>    </div>
  </div>
</div>
</div> 

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>

  <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>

  <% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>

  <%= f.submit "Save", class: 'btn btn-success' %>

<% end %>

app/views/wikis/edit.html.erb
<h1> Edit Wiki </h1>

<div class="row">
    <div class="col-md-4">
      <p> Guidelines for Wikis : </p>
      <ul>
        <li> Ensure your wiki is not a duplicate. </li>
        <li> Proofread! </li>
        <li> Fact check before posting. </li>
      </ul>
    </div>
    <div class="col-md-8">

      <%= render partial: 'wikis/form' %>

    </div>
</div>

app/views/wikis/index.html.erb
<h1> <div class="col-md-4">
  <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
</div> </h1>

  <div class="row">
    <h1 class="wiki-center"> Public Wikis </h1>
      <div class="box-solid">
        <% @wikis.each do |wiki| %>
          <div class="media">
            <div class="media-body">
              <h4 class="media-heading">
                <%= link_to markdown(wiki.title), wiki %> <% if wiki.private? %> PRIVATE <% end %>
              </h4>
              <small>
                <%= markdown(wiki.body) %> ________________________________________________________________________________________
              </small>
            </div>
          </div>
        <% end %>
      </div>
    </div>

app/views/wikis/new.html.erb
<h1> New Wiki </h1>

<div class="row">
    <div class="col-md-4">
      <p> Guidelines for Wikis : </p>
      <ul>
        <li> Ensure your wiki is not a duplicate. </li>
        <li> Proofread! </li>
        <li> Fact check before posting. </li>
      </ul>
    </div>
    <div class="col-md-8">
      <%= render partial: 'wikis/form' %>
    </div>
</div>

app/views/wikis/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", welcome_index_path%></li>
  <li><%= link_to "Wikis", wikis_path%></li>
</ol>

<div class="wiki-show">
  <h1 id="wiki-title"> <%= markdown(@wiki.title) %> </h1>
    <small id="wiki-submit">
      submitted <%= time_ago_in_words(@wiki.created_at) %>
    </small>
    <div class="col-md-16" id="wiki-body">
      <p><%= markdown(@wiki.body) %></p>
      <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-primary' %>

      <div class="user-info" id="wiki-box">
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
      </div>
    </div>

    <% if @wiki.private %>
      <% if Collaborator.exists?(wiki_id: @wiki) %>
        <%= render partial: 'collaborators/users' %>
      <% end %>
    <% end %>